### PR TITLE
Add regex support to query syntax

### PR DESCRIPTION
**Pull request by codchen**
## Describe your changes and provide context
Add regex syntax so that queries like `tx.topics MATCHES '\[.*,xyz,.*\]'` can be written and executed correctly 

## Testing performed to validate your change
unit tests

### CODE REVIEW

**Comment by jewei1997** [comment]
if we want this to be specifically the 2nd topic, wouldn't a regex like `'\[.*,xyz,.*\]'`  work for cases where it is the 2nd or 3rd topic? I think we might need to do exclude commas in the first `.*` to make sure `xyz` is the second topic.

**Comment by codchen** [comment]
> if we want this to be specifically the 2nd topic, wouldn't a regex like `'\[.*,xyz,.*\]'` work for cases where it is the 2nd or 3rd topic? I think we might need to do exclude commas in the first `.*` to make sure `xyz` is the second topic.

yeah exactly we need to exclude comma from the wildcard

**Review by Kbhat1 — APPROVED** [review]
LGTM, we tested this on a node too right?

**Comment by jewei1997** [comment]
> > if we want this to be specifically the 2nd topic, wouldn't a regex like `'\[.*,xyz,.*\]'` work for cases where it is the 2nd or 3rd topic? I think we might need to do exclude commas in the first `.*` to make sure `xyz` is the second topic.
> 
> yeah exactly we need to exclude comma from the wildcard

Oh I see this is just adding general regex support.

**Comment by codchen** [comment]
> LGTM, we tested this on a node too right?

yeah tested rpc request `Events` against local node

**Pull request merged**
